project:
  type: website

website:
  title: "Air Quality in India(2015-2020)"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: sources.qmd
        text: Sources
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



