project:
  type: website

website:
  title: "|.......................................... | 80% [unnamed-chunk-2]Error in `file()`:"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



